version: '3.8'
services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
    ports:
      - 3005:3005
    environment:
      - minio_endpoint=minio-container
      - minio_port=9000
      - minio_access_key=zhong
      - minio_secret_key=zx990927
      - mysql_server_host=mysql-container
      - mysql_server_port=3306
      - mysql_server_username=root
      - mysql_server_password=zhongjingbo
      - mysql_server_database=post_forge_system
      - nest_server_port=3005
      - jwt_secret=post_forge_system_secret
      - jwt_access_token_expires_time=1m
      - jwt_refresh_token_expres_time=7d
    networks:
      - common-network
  mysql-container:
    image: mysql
    volumes:
      - /Users/zhongjingbo/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: post_forge_system
      MYSQL_ROOT_PASSWORD: zhongjingbo
    networks:
      - common-network
    ports:
      - "3306:3306"
  minio-container:
    image: bitnami/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - /Users/zhongjingbo/minio:/bitnami/minio/data
    environment:
      MINIO_ROOT_USER: zhong
      MINIO_ROOT_PASSWORD: zx990927
    networks:
      - common-network
networks:
  common-network:
    driver: bridge
